### ISSUE TITLE
执行之后报错“订单提交失败”

### ISSUE THREAD

**Issue by Lyon0209** [xiaojia21190/jd_seckill_cli#10]
Error: Evaluation failed: ReferenceError: config is not defined
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:4:60)
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:5:15)
    at onRaf (__puppeteer_evaluation_script__:49:35)
    at pollRaf (__puppeteer_evaluation_script__:42:15)
    at waitForPredicatePageFunction (__puppeteer_evaluation_script__:7:22)
    at ExecutionContext._evaluateInternal (/Users/lyon/my-projects/jd_seckill_cli/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async WaitTask.rerun (/Users/lyon/my-projects/jd_seckill_cli/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:23)
订单提交失败

**Comment by Lion0209** [comment]
茅台的京东页面会出现一下然后消失
