### ISSUE TITLE
ubuntu 18.4运行不了，麻烦看下

### ISSUE THREAD

**Issue by ITdesk01** [xiaojia21190/jd_seckill_cli#2]
终端运行
`User@User01:~/11/jd_seckill_cli$ npm install
npm WARN jd_seckill_cli@1.0.0 No repository field.
`

`
User@User01:~/11/jd_seckill_cli$ jd_seckill_cli 
/home/User/11/jd_seckill_cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:707
        catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/User/11/jd_seckill_cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Target.js:19:19)
`

**Comment by 18657356139** [comment]
windows 也是
