### ISSUE TITLE
【shell运行报错】：Cannot navigate to invalid URL

### ISSUE THREAD

**Issue by lucia110** [xiaojia21190/jd_seckill_cli#3]
[jd_seckill_cli (main) $ jd_seckill_cli
? 需要抢购的商品URL，默认是茅台 -  y
? 生成订单需要的密码, 不写密码，最后一步无法生成订单  [hidden]
? 选择需要执行的操作 预约
Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at /Users/Project/my/jd_seckill_cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:208:63
    at new Promise (<anonymous>)
    at CDPSession.send (/Users/Project/my/jd_seckill_cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:207:16)
    at navigate (/Users/Project/my/jd_seckill_cli/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:108:47)
    at FrameManager.navigateFrame (/Users/Project/my/jd_seckill_cli/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:91:13)
    at Frame.goto (/Users/Project/my/jd_seckill_cli/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:417:41)
    at Page.goto (/Users/Project/my/jd_seckill_cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:784:53)
    at jd_yuyue (/Users/Project/my/jd_seckill_cli/jd_seckill.js:169:18)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  message: 'Protocol error (Page.navigate): Cannot navigate to invalid URL'
}

**Comment by xiaojia21190** [comment]
第一步，不用-y

**Comment by lucia110** [comment]
> 第一步，不用-y

好的，解决啦
