### ISSUE TITLE
下单失败，获取config的抢购数量时报错

### ISSUE THREAD

**Issue by aYu-live** [xiaojia21190/jd_seckill_cli#9]
Error: Evaluation failed: ReferenceError: config is not defined
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:4:56)
    at eval (eval at waitForPredicatePageFunction (:2:23), <anonymous>:6:11)
    at onRaf (__puppeteer_evaluation_script__:49:35)
    at pollRaf (__puppeteer_evaluation_script__:42:15)
    at waitForPredicatePageFunction (__puppeteer_evaluation_script__:7:22)
    at ExecutionContext._evaluateInternal (/Users/yu/project/MyProject/jd_seckill_cli/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async WaitTask.rerun (/Users/yu/project/MyProject/jd_seckill_cli/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:23)
订单提交失败

**Comment by xiaojia21190** [comment]
已修复
